# serverless.yml

service: cpas-login-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  login:
    handler: index.handler
    events:
      - http:
          path: /login
          method: post
          cors: true
  
  bff:
    handler: app.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /data
          method: post
          cors: true